
qcontrollerName: ""

image:
  repository: pinqituc3m/qd2-controller
  tag: "latest"
  pullPolicy: IfNotPresent

placement:
  nodeSelector: {}
  useNodeName: true
  nodeName: ""

l2sm:
  enabled: true
  networkName: ""
  ip: ""


service:
  enabled: true
  ports:
    - name: ssh
      port: 22
      targetPort: 22
      # nodePort: (optional)
